apiVersion: apps/v1
kind: Deployment
metadata:
    name: api-deployment
    namespace: music-service
spec:
    replicas: 1
    selector:
        matchLabels:
            app: api
    template:
        metadata:
            labels:
                app: api
        spec:
            containers:
                - name: api
                  image: music-service-api:latest
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 8080
                  env:
                      - name: PRISMA_CONNECTION_URL
                        valueFrom:
                            secretKeyRef:
                                name: secrets
                                key: prisma-url
