apiVersion: apps/v1
kind: Deployment
metadata:
    name: postgres-deployment
    namespace: music-service
spec:
    replicas: 1
    selector:
        matchLabels:
            app: postgres
    template:
        metadata:
            labels:
                app: postgres
        spec:
            containers:
                - name: postgres
                  image: postgres:16
                  ports:
                      - containerPort: 5432
                  env:
                      - name: POSTGRES_USER
                        valueFrom:
                            secretKeyRef:
                                name: secrets
                                key: postgres-user
                      - name: POSTGRES_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: secrets
                                key: postgres-password
                      - name: POSTGRES_DB
                        valueFrom:
                            secretKeyRef:
                                name: secrets
                                key: postgres-db
                  volumeMounts:
                      - name: postgres-storage
                        mountPath: /var/lib/postgresql/data
            volumes:
                - name: postgres-storage
                  persistentVolumeClaim:
                      claimName: postgres-pvc
